#' read NCBI names file
#'
#' yhid function reads from excel files generated by the ABI StepOnePlus. read from the (8) line and initial the cycles, return a list of lamp and melt amplitude
#'
#' @param rawFile string giving the path to an NCBI name file to read from (both gzipped or uncompressed files are ok)
#' @param rawDataTab the name of the tab Excel sheet
#' @param skip a number that tells where to star reading the file
#' @param cycles a int that set the range of the cycles of the lamp and melt curve
#' @param minPerCycle a number that says how many minutes per cycle
#' @return a list of lamp and melt amplitude table
#' @export
#'


readStepOne<-function(rawFile,rawDataTab='Raw Data',skip=7,cycles=120,minPerCycle=.5){
  dat<-as.data.frame(readxl::read_excel(rawFile,rawDataTab,skip=skip))
  dat$col<-as.numeric(sub('[A-Z]','',dat$Well))
  dat$row<-trimws(sub('[0-9]+','',dat$Well))
  dat$rowNum<-sapply(dat$row,function(xx)which(LETTERS==xx))
  dat$well<-dat$Well
  lamp<-dat[dat$Cycle<=cycles,]
  lamp$timeMin<-lamp$Cycle*minPerCycle
  for(ii in c('BLUE','GREEN','YELLOW','RED'))lamp[,sprintf('%s - baseline',ii)]<-ave(lamp[,ii],lamp$well,FUN=function(xx)xx-mean(xx[1:5]))
  melt<-dat[dat$Cycle>cycles,]
  return(list('lamp'=lamp,'melt'=melt))
}
